In [1]:
import os
import tensorflow
import keras

Using TensorFlow backend.

In [2]:
import pandas as pd

df = pd.read_excel ("Train Data.xlsx") #for an earlier version of Excel, you may need to use the file extension of 'xls'
print (df)

       age            job   marital  education connect  balance landline  \
0       58     management   married   tertiary      no     2143      yes
1       44     technician    single  secondary      no       29      yes
2       33   entrepreneur   married  secondary      no        2      yes
3       51        retired   married    primary      no      229      yes
4       57    blue-collar   married    primary      no       52      yes
5       60        retired   married    primary      no       60      yes
6       33       services   married  secondary      no        0      yes
7       28    blue-collar   married  secondary      no      723      yes
8       56     management   married   tertiary      no      779      yes
9       32    blue-collar    single    primary      no       23      yes
10      25       services   married  secondary      no       50      yes
11      40        retired   married    primary      no        0      yes
12      39     management    single   tertiary      no      255      yes
13      52   entrepreneur   married  secondary      no      113      yes
14      46     management    single  secondary      no     -246      yes
15      36     technician    single  secondary      no      265      yes
16      57     technician   married  secondary      no      839       no
17      49     management   married   tertiary      no      378      yes
18      60         admin.   married  secondary      no       39      yes
19      59    blue-collar   married  secondary      no        0      yes
20      51     management   married   tertiary      no    10635      yes
21      25    blue-collar   married  secondary      no       -7      yes
22      53     technician   married  secondary      no       -3       no
23      36         admin.  divorced  secondary      no      506      yes
24      37         admin.    single  secondary      no        0      yes
25      44       services  divorced  secondary      no     2586      yes
26      50     management   married  secondary      no       49      yes
27      60    blue-collar   married    unknown      no      104      yes
28      54        retired   married  secondary      no      529      yes
29      58        retired   married    unknown      no       96      yes
...    ...            ...       ...        ...     ...      ...      ...
40478   36         admin.  divorced  secondary      no     1224      yes
40479   34    blue-collar   married  secondary      no      320      yes
40480   34     technician   married  secondary      no     1026       no
40481   66        retired   married  secondary      no     3409       no
40482   46    blue-collar   married  secondary      no     6879       no
40483   34     technician   married  secondary      no      133       no
40484   70        retired   married    primary      no      324       no
40485   63        retired   married  secondary      no     1495       no
40486   60       services   married   tertiary      no     4256      yes
40487   59        unknown   married    unknown      no     1500       no
40488   29     management    single  secondary      no      703      yes
40489   32    blue-collar   married  secondary      no      136       no
40490   75        retired  divorced   tertiary      no     3810      yes
40491   29     management    single   tertiary      no      765       no
40492   28  self-employed    single   tertiary      no      159       no
40493   59     management   married   tertiary      no      138      yes
40494   68        retired   married  secondary      no     1146       no
40495   25        student    single  secondary      no      358       no
40496   36     management    single  secondary      no     1511      yes
40497   37     management   married   tertiary      no     1428       no
40498   38     technician   married  secondary      no      557      yes
40499   53     management   married   tertiary      no      583       no
40500   34         admin.    single  secondary      no      557       no
40501   23        student    single   tertiary      no      113       no
40502   73        retired   married  secondary      no     2850       no
40503   25     technician    single  secondary      no      505       no
40504   51     technician   married   tertiary      no      825       no
40505   72        retired   married  secondary      no     5715       no
40506   57    blue-collar   married  secondary      no      668       no
40507   37   entrepreneur   married  secondary      no     2971       no

      smart  last_day last_month  duration  campaign  passdays  previous  \
0        no         5        may       261         1        -1         0
1        no         5        may       151         1        -1         0
2       yes         5        may        76         1        -1         0
3        no         5        may       353         1        -1         0
4        no         5        may        38         1        -1         0
5        no         5        may       219         1        -1         0
6        no         5        may        54         1        -1         0
7       yes         5        may       262         1        -1         0
8        no         5        may       164         1        -1         0
9       yes         5        may       160         1        -1         0
10       no         5        may       342         1        -1         0
11      yes         5        may       181         1        -1         0
12       no         5        may       296         1        -1         0
13      yes         5        may       127         1        -1         0
14       no         5        may       255         2        -1         0
15      yes         5        may       348         1        -1         0
16      yes         5        may       225         1        -1         0
17       no         5        may       230         1        -1         0
18      yes         5        may       208         1        -1         0
19       no         5        may       226         1        -1         0
20       no         5        may       336         1        -1         0
21       no         5        may       365         1        -1         0
22       no         5        may      1666         1        -1         0
23       no         5        may       577         1        -1         0
24       no         5        may       137         1        -1         0
25       no         5        may       160         1        -1         0
26       no         5        may       180         2        -1         0
27       no         5        may        22         1        -1         0
28       no         5        may      1492         1        -1         0
29       no         5        may       616         1        -1         0
...     ...       ...        ...       ...       ...       ...       ...
40478    no        12        nov       482         1       374         1
40479    no        12        nov       413         1        92         3
40480    no        12        nov       319         1       100         6
40481    no        15        nov       414         2        27         6
40482    no        15        nov        74         2       118         3
40483    no        15        nov       401         2       187         5
40484    no        15        nov        78         1        96         7
40485    no        16        nov       138         1        22         5
40486    no        16        nov       200         1        92         4
40487    no        16        nov       280         1       104         2
40488    no        16        nov       236         1       550         2
40489    no        16        nov       206         1       188         3
40490    no        16        nov       262         1       183         1
40491    no        16        nov       238         1        -1         0
40492    no        16        nov       449         2        33         4
40493   yes        16        nov       162         2       187         5
40494    no        16        nov       212         1       187         6
40495    no        16        nov       330         1        -1         0
40496    no        16        nov       270         1        -1         0
40497    no        16        nov       333         2        -1         0
40498    no        16        nov      1556         4        -1         0
40499    no        17        nov       226         1       184         4
40500    no        17        nov       224         1        -1         0
40501    no        17        nov       266         1        -1         0
40502    no        17        nov       300         1        40         8
40503   yes        17        nov       386         2        -1         0
40504    no        17        nov       977         3        -1         0
40505    no        17        nov      1127         5       184         3
40506    no        17        nov       508         4        -1         0
40507    no        17        nov       361         2       188        11

      poutcome  target
0      unknown       0
1      unknown       0
2      unknown       0
3      unknown       0
4      unknown       0
5      unknown       0
6      unknown       0
7      unknown       0
8      unknown       0
9      unknown       0
10     unknown       0
11     unknown       0
12     unknown       0
13     unknown       0
14     unknown       0
15     unknown       0
16     unknown       0
17     unknown       0
18     unknown       0
19     unknown       0
20     unknown       0
21     unknown       0
22     unknown       0
23     unknown       0
24     unknown       0
25     unknown       0
26     unknown       0
27     unknown       0
28     unknown       0
29     unknown       0
...        ...     ...
40478  success       1
40479  success       1
40480  failure       0
40481  failure       0
40482  failure       0
40483  success       1
40484  success       0
40485  success       0
40486  success       1
40487  failure       0
40488  success       1
40489  success       1
40490  failure       1
40491  unknown       1
40492  success       1
40493  failure       0
40494  success       1
40495  unknown       1
40496  unknown       1
40497  unknown       0
40498  unknown       1
40499  success       1
40500  unknown       1
40501  unknown       1
40502  failure       1
40503  unknown       1
40504  unknown       1
40505  success       1
40506  unknown       0
40507    other       0

[40508 rows x 16 columns]

In [3]:
X=df.loc[:, df.columns != 'target']
Y=df.loc[:, df.columns == 'target']

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
df['job']=le.fit_transform(df['job'])
df['marital']=le.fit_transform(df['marital'])
df['education']=le.fit_transform(df['education'])
df['connect']=le.fit_transform(df['connect'])
df['landline']=le.fit_transform(df['landline'])
df['smart']=le.fit_transform(df['smart'])
df['last_month']=le.fit_transform(df['last_month'])
df['poutcome']=le.fit_transform(df['poutcome'])

In [7]:
print(df)

       age  job  marital  education  connect  balance  landline  smart  \
0       58    4        1          2        0     2143         1      0
1       44    9        2          1        0       29         1      0
2       33    2        1          1        0        2         1      1
3       51    5        1          0        0      229         1      0
4       57    1        1          0        0       52         1      0
5       60    5        1          0        0       60         1      0
6       33    7        1          1        0        0         1      0
7       28    1        1          1        0      723         1      1
8       56    4        1          2        0      779         1      0
9       32    1        2          0        0       23         1      1
10      25    7        1          1        0       50         1      0
11      40    5        1          0        0        0         1      1
12      39    4        2          2        0      255         1      0
13      52    2        1          1        0      113         1      1
14      46    4        2          1        0     -246         1      0
15      36    9        2          1        0      265         1      1
16      57    9        1          1        0      839         0      1
17      49    4        1          2        0      378         1      0
18      60    0        1          1        0       39         1      1
19      59    1        1          1        0        0         1      0
20      51    4        1          2        0    10635         1      0
21      25    1        1          1        0       -7         1      0
22      53    9        1          1        0       -3         0      0
23      36    0        0          1        0      506         1      0
24      37    0        2          1        0        0         1      0
25      44    7        0          1        0     2586         1      0
26      50    4        1          1        0       49         1      0
27      60    1        1          3        0      104         1      0
28      54    5        1          1        0      529         1      0
29      58    5        1          3        0       96         1      0
...    ...  ...      ...        ...      ...      ...       ...    ...
40478   36    0        0          1        0     1224         1      0
40479   34    1        1          1        0      320         1      0
40480   34    9        1          1        0     1026         0      0
40481   66    5        1          1        0     3409         0      0
40482   46    1        1          1        0     6879         0      0
40483   34    9        1          1        0      133         0      0
40484   70    5        1          0        0      324         0      0
40485   63    5        1          1        0     1495         0      0
40486   60    7        1          2        0     4256         1      0
40487   59   11        1          3        0     1500         0      0
40488   29    4        2          1        0      703         1      0
40489   32    1        1          1        0      136         0      0
40490   75    5        0          2        0     3810         1      0
40491   29    4        2          2        0      765         0      0
40492   28    6        2          2        0      159         0      0
40493   59    4        1          2        0      138         1      1
40494   68    5        1          1        0     1146         0      0
40495   25    8        2          1        0      358         0      0
40496   36    4        2          1        0     1511         1      0
40497   37    4        1          2        0     1428         0      0
40498   38    9        1          1        0      557         1      0
40499   53    4        1          2        0      583         0      0
40500   34    0        2          1        0      557         0      0
40501   23    8        2          2        0      113         0      0
40502   73    5        1          1        0     2850         0      0
40503   25    9        2          1        0      505         0      1
40504   51    9        1          2        0      825         0      0
40505   72    5        1          1        0     5715         0      0
40506   57    1        1          1        0      668         0      0
40507   37    2        1          1        0     2971         0      0

       last_day  last_month  duration  campaign  passdays  previous  poutcome  \
0             5           8       261         1        -1         0         3
1             5           8       151         1        -1         0         3
2             5           8        76         1        -1         0         3
3             5           8       353         1        -1         0         3
4             5           8        38         1        -1         0         3
5             5           8       219         1        -1         0         3
6             5           8        54         1        -1         0         3
7             5           8       262         1        -1         0         3
8             5           8       164         1        -1         0         3
9             5           8       160         1        -1         0         3
10            5           8       342         1        -1         0         3
11            5           8       181         1        -1         0         3
12            5           8       296         1        -1         0         3
13            5           8       127         1        -1         0         3
14            5           8       255         2        -1         0         3
15            5           8       348         1        -1         0         3
16            5           8       225         1        -1         0         3
17            5           8       230         1        -1         0         3
18            5           8       208         1        -1         0         3
19            5           8       226         1        -1         0         3
20            5           8       336         1        -1         0         3
21            5           8       365         1        -1         0         3
22            5           8      1666         1        -1         0         3
23            5           8       577         1        -1         0         3
24            5           8       137         1        -1         0         3
25            5           8       160         1        -1         0         3
26            5           8       180         2        -1         0         3
27            5           8        22         1        -1         0         3
28            5           8      1492         1        -1         0         3
29            5           8       616         1        -1         0         3
...         ...         ...       ...       ...       ...       ...       ...
40478        12           9       482         1       374         1         2
40479        12           9       413         1        92         3         2
40480        12           9       319         1       100         6         0
40481        15           9       414         2        27         6         0
40482        15           9        74         2       118         3         0
40483        15           9       401         2       187         5         2
40484        15           9        78         1        96         7         2
40485        16           9       138         1        22         5         2
40486        16           9       200         1        92         4         2
40487        16           9       280         1       104         2         0
40488        16           9       236         1       550         2         2
40489        16           9       206         1       188         3         2
40490        16           9       262         1       183         1         0
40491        16           9       238         1        -1         0         3
40492        16           9       449         2        33         4         2
40493        16           9       162         2       187         5         0
40494        16           9       212         1       187         6         2
40495        16           9       330         1        -1         0         3
40496        16           9       270         1        -1         0         3
40497        16           9       333         2        -1         0         3
40498        16           9      1556         4        -1         0         3
40499        17           9       226         1       184         4         2
40500        17           9       224         1        -1         0         3
40501        17           9       266         1        -1         0         3
40502        17           9       300         1        40         8         0
40503        17           9       386         2        -1         0         3
40504        17           9       977         3        -1         0         3
40505        17           9      1127         5       184         3         2
40506        17           9       508         4        -1         0         3
40507        17           9       361         2       188        11         1

       target
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
12          0
13          0
14          0
15          0
16          0
17          0
18          0
19          0
20          0
21          0
22          0
23          0
24          0
25          0
26          0
27          0
28          0
29          0
...       ...
40478       1
40479       1
40480       0
40481       0
40482       0
40483       1
40484       0
40485       0
40486       1
40487       0
40488       1
40489       1
40490       1
40491       1
40492       1
40493       0
40494       1
40495       1
40496       1
40497       0
40498       1
40499       1
40500       1
40501       1
40502       1
40503       1
40504       1
40505       1
40506       0
40507       0

[40508 rows x 16 columns]

In [8]:
X=df.loc[:, df.columns != 'target']
Y=df.loc[:, df.columns == 'target']

In [9]:
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
model = ExtraTreesClassifier()
model.fit(X,Y)
print(model.feature_importances_) #use inbuilt class feature_importances of tree based classifiers
#plot graph of feature importances for better visualization
feat_importances = pd.Series(model.feature_importances_, index=X.columns)
feat_importances.nlargest(15).plot(kind='barh')
plt.show()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

[0.10488957 0.05816097 0.02694925 0.03162658 0.00248651 0.10115543
 0.02700585 0.00796894 0.1015126  0.09434961 0.25201004 0.0623003
 0.04468442 0.02706206 0.05783787]

In [13]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(X,Y)

#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: operands could not be broadcast together with shapes (1,2) (15,)

In [22]:
df['keys']

KeyError: 'keys'